version: "3.9"
services:
  mqtt:
    image: eclipse-mosquitto
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto_data:/mosquitto/data
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto_log:/mosquitto/log
      - ./pass.txt:/pass.txt

  grafana:
    image: grafana/grafana-enterprise:8.5.2
    environment:
#      GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource,grafana-worldmap-panel,grafana-piechart-panel,satellogic-3d-globe-panel,macropower-analytics-panel,ryantxu-annolist-panel,michaeldmoore-annunciator-panel,anodot-panel,volkovlabs-image-panel,farski-blendstat-panel,yesoreyeram-boomtable-panel,yesoreyeram-boomtheme-panel,digiapulssi-breadcrumb-panel,digrich-bubblechart-panel,cloudspout-button-panel,neocat-cal-heatmap-panel,marcusolsson-calendar-panel,petrslavotinek-carpetplot-panel,snuids-svg-panel,integrationmatters-comparison-panel,briangann-datatable-panel,jdbranham-diagram-panel,marcusolsson-dynamictext-panel,larona-epict-panel,marcusolsson-gantt-panel,grafana-guidedtour-panel,mtanda-heatmap-epoch-panel,marcusolsson-hexmap-panel,mtanda-histogram-panel,marcusolsson-hourly-heatmap-panel,aidanmountford-html-panel,gapit-htmlgraphics-panel,pierosavi-imageit-panel,natel-influx-admin-panel,flaminggoat-maptrack3d-panel,thiagoarrais-matomotracking-panel,boazreicher-mosaicplot-panel,michaeldmoore-multistat-panel,orchestracities-iconstat-panel,isaozler-paretochart-panel,zuburqan-parity-report-panel,sskgo-perfcurve-panel,scadavis-synoptic-panel,corpglory-progresslist-panel,mxswat-separator-panel,isaozler-shiftselector-panel,boazreicher-sierraplot-panel,grafana-singlestat-panel,blackmirror1-singlestat-math-panel,blackmirror1-statusbygroup-panel,flant-statusmap-panel,marcuscalidus-svg-panel,gretamosa-topology-panel,gowee-traceroutemap-panel,alexandra-trackmap-panel,pr0ps-trackmap-panel,snuids-trafficlights-panel,smartmakers-trafficlight-panel,innius-video-panel,auxmoney-waterfall-panel,fatcloud-windrose-panel,magnesium-wordcloud-panel"
      GF_PATHS_CONFIG: "/etc/grafana/grafana.ini"
    volumes:
      - "./grafana_storage:/var/lib/grafana"
      - "./grafana.ini:/etc/grafana/grafana.ini"
      - "./grafana_logs:/var/log/grafana"
      - "./grafana_plugins:/var/lib/grafana/plugins"
      - "./grafana_provisioning:/etc/grafana/provisioning"
#      - "./grafana_home:/usr/share/grafana"
    ports:
      - 3000:3000
    restart: always
    logging:
      options:
        max-size: 10m
        max-file: "3"

  timescaleDB:
    image: timescale/timescaledb:latest-pg14
    restart: always
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "admin"
      POSTGRES_DB: "mqtt"
    ports:
      - 15432:5432
    volumes:
      - ./database-data:/var/lib/postgresql/data/
      - ./mqtt2postgres_bridge/setup_db.sql:/docker-entrypoint-initdb.d/setup_db.sql
    logging:
      options:
        max-size: 10m
        max-file: "3"

  # to connect from your host machine you need psql:
  # sudo apt-get install postgresql-client

  # if you want latest version 14:
  # sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
  # wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  # sudo apt-get update
  # sudo apt-get -y install postgresql

  python2postgres:
    image: python:3.9-alpine
    volumes:
     - ./mqtt2postgres_bridge/pip39:/usr/local/lib/python3.9/site-packages
     - ./mqtt2postgres_bridge/bridge.py:/project/bridge.py
    working_dir: /project
    command: python bridge.py
    depends_on:
      - requirements
      

  requirements:
    image: python:3.9-alpine
    volumes:
      - ./mqtt2postgres_bridge/pip39:/usr/local/lib/python3.9/site-packages
      - ./mqtt2postgres_bridge/requirements.txt:/project/requirements.txt
    working_dir: /project
    command: pip install -r requirements.txt