name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      #- name: python-isort
      #  uses: isort/isort-action@v0.1.0

      - name: python-flake8
        uses: julianwachholz/flake8-action@v2.0.0

      # - name: pylinter
      #   uses: alexanderdamiani/pylinter@v1.2.0
      #   with:
      #     fail-on-isort: false
      #     skip-mypy : true

      - name: Run tests
        run: pytest -v
